{% set name = "rollbar" %}
{% set version = "1.0.0" %}
{% set sha256 = "6347b7e49f22f0296fc287a6aea75d642cf64494d2ee127042a7a593c97df3af" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - rollbar=rollbar.cli:main

requirements:
  host:
    - python >=3.3
    - pip
  run:
    - python >=3.3
    - requests >=0.12.1
    - six >=1.9.0

test:
  requires:
    - pip
  imports:
    - rollbar
  commands:
    - pip check

about:
  home: https://github.com/rollbar/pyrollbar
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Rollbar notifier for Python

  description: |
    Python notifier for reporting exceptions, errors, and log messages to Rollbar.
  doc_url: https://rollbar.com/docs/notifier/pyrollbar/

extra:
  recipe-maintainers:
    - fpaniagua
    - TheOriginalAlex
