{% set name = "rollbar" %}
{% set version = "1.1.0" %}
{% set sha256 = "0894302f7caf3d1f16c84ae3d609dc6385fcdba95ae78c9af1f4809a7dd44a89" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - rollbar=rollbar.cli:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - requests >=0.12.1

test:
  requires:
    - pip
  imports:
    - rollbar
  commands:
    - pip check
    - rollbar --help

about:
  home: https://github.com/rollbar/pyrollbar
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Rollbar notifier for Python
  description: Easy and powerful exception tracking with Rollbar. Send messages and exceptions with arbitrary context, get back aggregates, and debug production issues quickly.
  doc_url: https://rollbar.com/docs/notifier/pyrollbar/

extra:
  recipe-maintainers:
    - fpaniagua
    - TheOriginalAlex
