# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  name: rollbar
  version: "1.1.0"
  build_number: 0
  python_min: 3.9

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/rollbar-${{ version }}.tar.gz
  sha256: 0894302f7caf3d1f16c84ae3d609dc6385fcdba95ae78c9af1f4809a7dd44a89

build:
  number: ${{ build_number }}
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - rollbar=rollbar.cli:main

requirements:
  host:
    - python ${{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >=${{ python_min }}
    - requests >=0.12.1

tests:
  - python:
      imports:
        - rollbar
  - requirements:
      run:
        - python ${{ python_min }}
        - pip
    script:
      - pip check
      - rollbar --help

about:
  license: MIT
  license_file: LICENSE
  summary: Rollbar notifier for Python
  description: Easy and powerful exception tracking with Rollbar. Send messages and exceptions with arbitrary context, get back aggregates, and debug production issues quickly.
  homepage: https://github.com/rollbar/pyrollbar
  documentation: https://rollbar.com/docs/notifier/pyrollbar/

extra:
  recipe-maintainers:
    - fpaniagua
